---
- hosts: all
  vars:
    - homebrew_installed_packages:
      - gettext
      - git
      - texlive
    - homebrew_taps:
      - homebrew/core
      - homebrew/cask
    - homebrew_cask_appdir: /Applications
    - homebrew_cask_apps:
      - 1password
      - discord
      - docker
      - firefox
      - istat-menus
      - megacmd
      - megasync
      - protonmail-bridge
      - slack
      - sublime-text
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew