---
- hosts: all
  vars:
    - homebrew_installed_packages:
      - biber
      - gettext
      - git
      - texlive
    - homebrew_taps:
      - homebrew/core
      - homebrew/cask
    - homebrew_cask_appdir: /Applications
    - homebrew_cask_apps:
      - 1password
      - 1password/tap/1password-cli
      - discord
      - docker
      - firefox
      - istat-menus
      - jabref
      - megacmd
      - megasync
      - obsidian
      - pdf-expert
      - protonmail-bridge
      - slack
      - spotify
      - sublime-text
      - telegram
      - typora
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
    - mas_installed_apps:
      - { id: 441258766, name: "Magnet" }
      - { id: 1278508951, name: "Trello" }
    - dockitems_remove:
      - Launchpad
      - Safari
      - Kontakte
      - Notizen
      - Erinnerungen
      - Karten
      - Nachrichten
      - FaceTime
      - Musik
      - Podcasts
      - TV
      - Bücher
      - 'App Store'
      - Systemeinstellungen
    - dockitems_persist:
      - name: "Firefox"
        path: "/Applications/Firefox.app"
        pos: 1
      - name: "Terminal"
        path: "/System/Applications/Utilities/Terminal.app"
        pos: 2
      - name: "Sublime Text"
        path: "/Applications/Sublime Text.app/"
        pos: 3
      - name: "Typora"
        path: "/Applications/Typora.app/"
        pos: 4
      - name: "Obsidian"
        path: "/Applications/Obsidian.app"
        pos: 5
      - name: "JabRef"
        path: "/Applications/JabRef.app"
        pos: 6
      - name: "Trello"
        path: "/Applications/Trello.app"
        pos: 7
      - name: "Kalender"
        path: "/System/Applications/Calendar.app"
        pos: 8
      - name: "Mail"
        path: "/System/Applications/Mail.app"
        pos: 9
      - name: "Telegram"
        path: "/Applications/Telegram.app"
        pos: 10
      - name: "Discord"
        path: "/Applications/Discord.app"
        pos: 11
      - name: "Spotify"
        path: "/Applications/Spotify.app"
        pos: 12
      - name: "Fotos"
        path: "/System/Applications/Photos.app"
        pos: 13
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
    - role: geerlingguy.mac.dock
