---
- hosts: all
  vars:
    - homebrew_installed_packages:
      - biber
      - gettext
      - git
      - texlive
    - homebrew_taps:
      - homebrew/core
      - homebrew/cask
    - homebrew_cask_appdir: /Applications
    - homebrew_cask_apps:
      - 1password
      - discord
      - docker
      - firefox
      - istat-menus
      - megacmd
      - megasync
      - pdf-expert
      - protonmail-bridge
      - slack
      - spotify
      - sublime-text
    - mas_installed_apps:
      - { id: 441258766, name: "Magnet" }
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
